name: Vanillahungergames
version: ${project.version}
main: me.crazycranberry.vanillahungergames.VanillaHungerGames
api-version: 1.20
authors: [CrazyCranberry]
description: Vanilla hunger games where players must craft their own armor/weapons/food.
commands:
  hgcreate:
    description: Start a hunger games tournament
    permission: admin
    permission-message: You do not have permission to create a hunger games world.
  hgjoin:
    description: Join the hunger games tournament
  hgleave:
    description: Abandon the hunger games match and return to the original world
  hgclass:
    description: Set your class for the games
  hgclassInfo:
    description: Get info about a certain class
  hgclasses:
    description: Get a list of all classes
  hgrefresh:
    description: Refresh yml configurations
    permission: admin
    permission-message: You do not have permission to refresh.
permissions:
  admin:
    description: Vanilla Hunger Games Admin permission
    default: op